### ISSUE TITLE
Better exploration-based achievements

### ISSUE THREAD

**Issue by bernardosulzbach** [bernardosulzbach/dungeon#122]
Some suggestions:

I need no sunlight
- Discover 10 new locations at midnight.

Morning walk
- Discover 10 new locations in the morning.

Child of the night
- Discover 20 new locations during the nighttime (the dark PartOfDay values).

Child of the light
- Discover 20 new locations during the daytime.

Insomniac
- Discover 10 new locations in the night.

Remember: **at** midnight, dawn, noon, dusk. But **in the** night, morning, afternoon, evening.

**Comment by ImmutableBox** [comment]
I would like to work on this issue.

**Comment by bernardosulzbach** [comment]
No, nothing in particular. Feel free to add other achievements if you come up with any and to not implement all of these if you find an issue.

**Comment by ImmutableBox** [comment]
Hmm, looking it over this seems pretty difficult. The `ExplorationStatisticsEntry` doesn't keep track of the `partOfDay` when the location is found. If I add a `PartOfDay` field to `ExplorationStatisticsEntry` I would be adding/editing code in a lot of places to store the new 'PartOfDay' field...

Should I continue on like this? or is there a different solution I am missing?

**Comment by bernardosulzbach** [comment]
> @bernardosulzbach Hmm, looking it over this seems pretty difficult.

I think you will be OK.

> Should I continue on like this? or is there a different solution I am missing?

It would probably be better to store a org.mafagafogigante.dungeon.date.Date. We can derive part of day from dates, and it allows for more achievements to be written using date-based rules in the future. I am unsure about the amount of work, but I don't think it is too difficult.

**Comment by ImmutableBox** [comment]
> 
> 
> > @bernardosulzbach Hmm, looking it over this seems pretty difficult.
> 
> I think you will be OK.
> 
> > Should I continue on like this? or is there a different solution I am missing?
> 
> It would probably be better to store a org.mafagafogigante.dungeon.date.Date. We can derive part of day from dates, and it allows for more achievements to be written using date-based rules in the future. I am unsure about the amount of work, but I don't think it is too difficult.

OK, Ill try that. Thanks.
